### ISSUE TITLE
error module not found for all scripts using NaNGFNoise

### ISSUE THREAD

**Issue by RosaWagner** [NaN-xyz/Glyph-Filters#45]
```
Traceback (most recent call last):
  File "DoodleShadow.py", line 10
    from NaNGFNoise import NoiseOutline
  File "NaNGFNoise.py", line 1
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

```

cc @simoncozens

**Comment by simoncozens** [comment]
This is one issue I'm trying to work through with Luke. We have two options:

1) Just install numpy into your Glyphs/glyphsLib environment. This is much easier at the command line if you are using glyphsLib and `run-filter.py` to filter the fonts, which I would recommend: `pip3 install numpy`, job done. It's much more complicated inside Glyphs, because Glyphs has its own Python and users can choose a different Python, and everything is messy. There is a [forum thread](https://forum.glyphsapp.com/t/better-method-for-installing-python-dependencies/26972/10) about how to install numpy inside Glyphs.

2) Do we really need numpy -> do we really need Perlin noise -> audit the filters to see where we actually need Perlin noise and where we can just get away with ordinary random numbers. Luke is (I think) working on this.

**Comment by simoncozens** [comment]
OK, I solved this a different way. Now we are using the `noise` module for command-line users, and I've supplied a pure-Python port of `noise1` for in-Glyphs users. This *should* give us compatible output.

@NaN-xyz, I still think reviewing whether you're actually using Perlin noise or just random numbers is still a good idea.
